---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: audit
    image: node:12
    commands:
      - npm audit --package-lock-only --audit-level=moderate --production

  - name: install
    image: node:12
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true

  - name: test
    image: node:12
    commands:
      - npm test

  - name: check-coverage
    image: node:12
    commands:
      - npm run check-coverage

  - name: build
    image: node:12
    commands:
      - npm run build

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: docker
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: docker_username
data:
---
kind: secret
name: docker_password
data:
---
kind: secret
name: ssh_key
data: AA/qyHjFPM6cSClQtEllz2qHJj0Toh5/WvUusErqJdlXGfTAxhessfvQEJLN0Hf6sKssEIUPlJP9s9+4LPcbMX9eMoUzmHrldBPXMNFomVFarC3J5FB0ngnEzxfOwt0g1vYStkQKTxx6B8+v4Muedozs2Mtoo098n6Gd20sAADwDPlt7EpY2bp4AbNCWdx8nkkfv7B+duLkmYPpCkpLeAWTNLvREgn9K5AnjlsJ+xC8tKT8dvDCHKRWnG11MKWVh/XQuUTMh0zXOSdvI7whN6Pb/JsWGM8ie3f80WPrwOXAL/5EPAzcdrlL+/TMAd1z/P4gm7Y6SbSWnZKBBV66qFkvGLIGp5fzI47kSxUrLnSqEamDwq4DVIX9i7vGGboKnJr+ScK2rahOvv3UzTEvqF39quctnmcPFXjChOyKIaH7gPKsG4/eyU7IQpqcF0EZ9uKaGOnekgUQD3Rw8P8n3Td4Je/eU9CkZhkzfkghEf18Ag8B69CWk86TAyFpIytTndqvbD9QParMnSnAOjc3Phakjq+fkNooYVk/Q0fE6Fcl/y9UJXjqwtGAew+ejrX5CQfYqBnIQn3rOySBEGjRrLsouuaGzGibEcVlLPRM4KLxdpVlnDG3OTZjoau13BZx8cvEqtWtTcM4cHUI42mM/rrJgzVReBzytd4n67EgWIqZzuZ+LTgxwvX5iZF5wITlcNPBUYS7wbR/DWKs8xJp3f/Uv4o175MhyeK4es+05sktO7rWdRztH1HTDXkX4xj3mg+kcy9IGnAr5WUWotiiZKb5b+2Il1+tjJUgUzZUWD+rJj6Y3JVld9PJkICHly6EK/S/R5HKe/O8rvs9Cy3Tiv/guWkiukkm1eCo/tzMdneqXcAYAE2Lsjq5/KZCsyGd0it87KWUE/EMgu1hHDx0QHlVAr9J9N+rpE8BCxMR/xTD8iyz3IPrktQ4AzdQhWyFUcCm2W1m8vNAXo0Vlbb+vABCYsC9+z84g+UwC40CYzZtID8cHdmFHUPPk5lnuFL8TnjNmkMFDrPph67DhIqJ0brjmr+fuv2QF6OUYBABDKPzy2AgNddlyDrFmt/ec/QqdwAmJamPizUC0WDUMvqOMF7KqOVmE7rFJBP6oFMOCbQBsK3M0LJEY8I5iYle2h7c2YZtDYuA3fukLl3C1UdfrKJ7FTo+O7NcXKYCHN+apurkGDdJ0OOBhp941hwJekXz74P+WUbFBgfGIToUrsGyKhH6j0pZLmEYo8sCO8azNxIryKPwY8dp/P/qATWoAcTOqImXYbPmYRQWsRlxjDEufh/Zh9O6J+aW8zUkYHrUJhmXXOKyNk4AmdX9wIPvpx2x6zlDUF22PFTjjEdcZ9Rm9QpBhbYJg75xP7OIugG45m55y79n7PrarjMa3Qe1PTao5xQla8xw/afXq+mvfnKRPlEW5W9Ei7j6Ud6IsSqS+AiHlqd7MEvRR4SHNZQFvyhvuoH7i7vd7l8yu17D5XBKqZ90h4BzKjQyBLPc86NfvOzshDhK++sq1ccoOwjrvSjFJJ5F7CF5rhAuPsjeJBYSHvOX2vhvdaa9/sl/7JMt9DveH1VmpYLDNJvcG9pUna8bhAZp6JAwXaoItRTR2K0HJVRt7jXMOzZwqm1qp92UM6AZarUPBoNZvj320IXbehUWUcmooyUwFGSdqwYMmFTQnGULjvX02ADMuI6g/nzBZ3lwbs+0JM/WT9GSApUnnlbPQ5P1RurrH1BThNUcCcTvwdBQQ+UA9Y2PmCu6gDgQiKrZIpT/DjEVL0FkUo8V8cnbAFrCsw+QST4HQVdsO6I+ox8w/UsTxXDpyietVMNVwt6q+o8SmCMX7MGLPlCkAp9fwbhnQu21hgD+Evx6uj0YbA0ke7kjduwvvkZ1jux+xZFxe5AAmeFLIyXI+uxhA/t1gIzd1n/lwk7vLxtqbIJd+0SzhK0yZsLmyYhlDwgkS38VffIPW3vMwnLzo6v+xsMh4rxRy3azUgy0a+0YZ75EZrgUY2RmtWFFDYtcR2Jlo30EkWZa8NBkooFyL6UL3VpnfQ2IjeFJXVJfFAW6xBOQfmaY7fKA85NLREhHcw+P94xPLuYcDNi+Bz9aFnOU/aAp1DHWPWOCqy3tzr5OEesNoSNxv/b867Z8TwAwyuZpXLsfIbFd15FW1uy9yM52M+7MXQk2tJsNBL+xTHb54k16gz6noGqW7P7mNmxt7y9BPq4Kz2fP07R8qLXSkANQAWSgX9x3bRbkm5z43HN/2nm9vcy4TkEyps76+z83LE4+afeYAwf+iTomXQsWOHOwBAUwHejRPy0PeGSvM4PSLckYPHMiNuyxut+096CiCiYnoyv6nQxh+TqrWWxdihMFSdT6Z21qnthjIhisGahVYUS0RKABbT3gtQwlYtIplrrYFxy8reZq/XThZ5omyMyhFsfQDjp/kaVXogfBlY3ptQC6pcaJxXQTyuTlw1snKR/9GhBZwMnlw3I6L5gJAj020hSaVRfzpa6KmZbSN/XpRu5xQzQSvCyX8+aphimWB2Q2D/59ITzW/NnAf1HfdhYq1fvCsgVFgU04nrFPje5iE7O7P6DGj1yFMmS0ZBt762rG+1Ux8Gy+kTACYfMf/F//qjDaGj4gA+PpyTZiP5NBMRuAQnqv/CJzy/ZRdm7r6BWhwKNM6enSnw1T59Imi81OdxeVwAuogutK16+bCptjMcRHuNkN9me7ZlkHUFJn/XQFy/kXDrGxTw6aUb8k+nbS3HdnEfcAGBw5ZJBZahCM27xI2B3gA+iaOGDr93vR3qd0JjUvZQyfAGC22eEtbDXxHFvifRwyu23REtewYeHJAeROA0xUn87DMxDVond4nHf9S4RnmaYM1tMDjLCLI4sk36+71qf1v5vkjAroge69gpKueTEfH4pAFDUVgzJA1l6RTMDWKodTpo1CDCDt2EwWVQSU4EDuNjBvHzK4jcqDHb9eFd6oLY/QohbbGtA6UI1FSmQIh7wIoXULnXl8tOym0gp3bxQLulOaIq/QIngjZ
---
kind: secret
name: gpg_key
data: AWwTH6DSQpVcz3oYW7zBGfy6+ZQ5YTRbNWHiqIBNYrcnyTTBImfOTaP8znkQ3cPonPVZJTuO0R60jeY92r/8d7yNwrThQzQGChLSdIHnzdGmS7MxvMIQS3pGVBZkO22nkM8wgeUoXYRaXRncznw5lBjqjNmdHlIfIc2eFUTiMITQjgSMoR0D4GXAxrpgfkttdXGd9BtefmFL2hPD/tUSKdL6HmHC/1HmaQ+i1vrcOLcehfnhD1nLVCeYBHHSBmh1L4cY4iJGlB2IEptDUQIz6tS967U8J/D5tSAIX0aSQMxiPMKGJKLxMnZuez3tLx7IPZlxsC8iSqY5vIrV3/zuf01+YUsgtE+0lGyzUuuNaJr3OfI9nhl9jf35PwdxyFJJlzqnljR0dc52mnsFWwX0Wj+X0BO6ddulfz+ZsYBH8Srfr6pyKKuF5V9GQ+kjZ1eVY1FqaXa7rSTzSiYYFbgx0MqxrS6YWTvG6R5rdQ4gjcbp8KCIr2cV4wPlQnMEKbYY2+hdKjQIZ82kIxmQ9X/3TaHbMtw2QYDt3wzSRPz0dxPb/snKmQ01PE4gcQfIZjOHVvYVFn7DLe1yqdObOmI0k8XoVNDLmfJvEUqfrfz5TQJObzUzhUon7F55lPubyFUeIPQHsrLqiXAh1lwe8SsbS+OlpkPC16wu7exGHkt4rR+u+ddvncTrpVY6PQlkYrLUfpXkLcHzicn7lJsSwqdP3MBQYYsHuLsvFTVv9/hMOY9i1JbB1roIxmlJo3CgHIQTgCxOBCJ8AoB4RXXGPYUbusFkyWNCNAxwlI6Dif/eyzWFQ+O2TRxkopEGQpqaokYFtrV+7PGfSvLrB48SgsCBNS6g8s3DlO49oa3D4aNiXT1Tq+sTxN1hEEJmh5aBfpuxiHvHGeS11bk66scrQ4lYsJYnW3Qtx5nn+/3rXTGtuaRQjVt51YSEPBMOgIP4CmXs5AEmgu8WtLmLLNWKH8Pzl4e/WPovSNY5JTtf5XuI/DnyQEao1ByMKrnc5de8Wn7yYUYRUxwd7Bz9P38YQOnPNnujs41nV6yfZs33vcVF5U0dBo7UcecQ7t/kuX5HP8GWW1WPyIcu3dWvCJOnVFhVNlpIoUiCCRxN3VLL4y6pMMRZ+53aBfXYpxw4AWlp1Q6I2Bz3sme49JTGP4WswxyGpwDf0MeEOZxc6BLE2WSl9OPAIzC8Uta9tZ6LCrwdcE58+7OBSKAB6cNVF4AdkT1Y1IbBAZhGP+rQ+SZLa97wr1b6FkYz3HwV1zdDLCNjNNgaHRVE9+XwnTot46QYQ6NNZQqnFtC92leBOiUg7wBsFwEywTvR6ZCFZaVKJ64UOvt+4bvqgdNBdRU1Avd+Dp5RbyESmNIg+6IXiiKDrlVsHXbpqmawy0eOpPHMmLPBgX+7tbom2apUGFz4NWRjjemICOz6sMSDCE/kMWJKHcUfyNA01Y/L+AWTbRa93gY02KoaCdHyPXkUS5J1zI4C8N2CsYQO8qT3aGs0sXK4nHWCu+5bgyLKNgS1A32fEnUsejjxQ9PSpbqhEqpeE2o04Hm2HwpjgVcc9RMFDWJF2P4mjTLzxwhXaEoLPcc0M0pYxgKb9jpfMjRtSBQEb5LY4SP6Pf4DAXFSASdnvHValT+qSQswQw631kgPv9TTZ0QjnnY57QTzmGSmUbfxKSwYSphikINefBhggoecosGh4eDkxd1+QEzu6BOA6qzEWJJ7rxGmdjj4QJp+x0258ewS5gvn9o8b7+9mAPqToERQ/LTEvGQ2Ehth4FFamnkp0r7E0TCbfTm3soxhfd2rUq6T5GcDH1/+ev6p0v5a/7pjY1zRVyjX0/CXSbOQLXdM9FxS/r7nzghzQjLNW+9A/WDEZAnCWkPNwLlUuHqNFZpgcuOJiYbA8QzPUMtHFclPFg7YwfN1TOuX6riFLNfuSvD8MITTnVOwnvlN81vGoCwiRsAbElQLHqT39Kka2SQAFt5ZexF5OVqmQVoMDyrIKyd6V6y0ZgliXQa2CSF7ECmNHFlzZ57SuMMXe1KD4ZNUzDLPeNFuYYVypmt1LClvaJtScLZcnb3CBLMGbh1lHd8VVg4dbFfRzNIZiHNm9/da8w4CvPElc5lFbwH6vvgiUsXLIRNF1CPjIdSeg22Y3uAJy03sa7hhRp0jJioHx14aY0J/BCtE0rCRi6NkfTh3F7KyrnDXKhcqcIrcpHsD1NoYJjvOrNotGmcjkw90tVY2k4JIYsWF4MlxNidwLGHNAZlVxNDPfJk/b0GcM2t24o7z084+Jd3XIQJc1Bwr9HKdLhqpzpJdytGqgnAy/r4ZRRnpGYHtTycF5CO60X8unzwLuND8t/htszcrj2+e8DWUD/LMv/OpHuUo3SAogEc7+X1sqqDZDxVwJt+wZsSc84l7rkzQkbRAhVJlfpGD2gk0KzCcefZWfXSYUWuNOUi/ml7Wauv7ML3hBXt3+jKnNyI6K5BHyTFPlk7eKOr++bUJi3DjWX9pO0p4x27Z6LjGyXgXDlmou1wdecDjdXkSlqnAMHhl9V63JoUx7N8kHAI4xDgZYdC71bnNgn5mgBfYyG7i/EsPTxcBFeOAiUYYpkfJzyOLfiKZJT4JiQ0G1xRHbU5G82HI5aHoHnESRtvwdo1mFMnNnBdz1b53A8hr0ohwZDOgDLVDAWxfcTfs56gpOr2LKEgzJZF3wuc+OQ3fJH7Ka1xBS+DXNQvuLGekEK/2GX4dyDePEfeD9p5U5PR1/d01dJqaW0aShNDMz89BnfXUOD1bP2cT4i/OOEo5dLnBYLpeIEyb4Bcikncggr1IPHEEXXuDCccffpMoJ9SgGu8C0GHOKUF1WVREsp4VdvNSkMPFdYhlX4QaYC0mtrdAfPdwD8rH/jVdmvSN47XGUsxxE3Ho7WL1wnljrzHyBA/cCjmkQr742Pl2vpSaBoj/pryIk+H0NiXhe5ZAugRvfASNxP8RFjSDMEKe3r9XEJq8+DLIkhOPrLFjb7Uow4K3ln81eGbRuj/iGf6S9rQqVEJMxBSYyAJuXCyZlf2ohFnQycOeXqSX8BXt9hAbvEK8crgI8T0LqdyYLIoAPiJ2+01tjf/zrMIKA8nsad7CfYWooatH+gp4+2BAVTRlLUgUxLTH1ozeow+BfIi70oNtSDE9hen3Pc3sNxANGrlzbfeNpp5FxIJTsumQEKettjFrhBJIy5PHrorFGIRSrsdjLeYitjWCi0JJxxxNO5Prjv3dcixn0T93dHWkCZAIxcAk7P4d049+zzlVKjmRfp8lmVUNARDQ9ChSmiqKpOBwpxuDI2QtQ5kH43uXfNEqQtfaQiTSBrVr7hvaD4dlldipXrRWjkPMqA96kFsaVxDOwcPc3BCxhB9P6b0ES09xEjkREUWfOtZ31cVwCL/26ACJb4mZ2wa885oL8CjPhe0nlISX4lb+haNP3sNP+6NEyo/Rs5um+FFl9v61HZqR5UP/GpPD9u/cc7I5gWT2C3/1mDfr14gcmpShlSjK+osHjgHy3YVsJQkx4ZnBXzhBtDEUxSQ3u6sQSGtQumC6vNjLxF9OqSAZSFdlwa5hB4CKaqwJjsWPLA8WUChW8ZmVfy6QOxPC0KohTjx1spJcXSQBrbomOZfhX/o74Q5VOsIeXGmY2qkF/8WUic/fC4GdaZOUadj47MclcImEknoIvKuTpencYOBgxlBh5NPdUnUIiFONqy9AJgcQVKp+ZNZ5cMHo/dvNbWAGMrmSXpl1ilD9gJwD6C+NxvrFPc4TbNyRa5ta+sNmYc6O6HGLk0mJCmpKtarK2pHjOMThClP2RBuCBtGTIBgAXqbqWKHvduv9eo8wPm9VSmX7hXYgwaW+C9YevPCSEbhaxc0hsSGnaAXRcqb6t/15n8cHe3ZWvAiSVDybcNruawA7t/UykLo0h8WOPFn0fVUSssMswIfNKdz6tBIFHzJz4mmku+h4n2lGVM04uReMY3MsiY0q4VjoOvAaV+/XKsZoinNzc1vrrTc2Jhx3p0hV1moxAKlMSMvLvXQAR0fvoR7lsTOmzGoLXTKwuULFLrOyKqPz43Gmkk/Q2kmFDLUbyxApm/dMNuerQjCshmy59Foxaa9l9J3hwfk/4yDDfCEPyewVvwPTZj5Qc1rGqo9w1F6K8fPQUhd1dWMQJGolkEDlh6jR808lBVc2/yY77oe9wH+/mAlGYq2m+2oJuuaC42o25udp07Mk7EeSXVEEwRkclCPHKZkJ5x9TVPfMgJNfF4r/5lSZ5ivVa/HrOPhGoxId+y7e9SIDq1jzMx2+PCEEPwUTkNrnHMqIL70MioImkwWLqmZO7iflwPC2W8wBwo3sN103LMHkDieZcFTNSQ5RK+ioOx6LqduepGlfskK5Y5OjoxymNufWhZcfuASWVd31aG/7v9PIEzb4JOOBG7AhzoMi5gFqw8F1Fcg9Gn1TheJ2iuxFe3NqzenKouchULFU1ntVdjDlYy5wRq23gxH9ogYWbG623H4BzgMRrRx8TF6i0fKMn1wU1/MeRl66yNuBTq/krvp83IC/+/Mjv3L9kJHs34dmAOrhn+WQdn6WyN3QNXU3wngPpItNaYGAUdhL4gbVsbnlj6FaDUymMZPp58HYOSnjKd02bmv7gjjH8SAnCtPzGNfpWfX7cn2em51vSfYNHiMvJc09hTDbTDDMqp0KIT/5EoZj5rKkTwJ0d3weLqicNz+Z5P9ZSlibnE92Pfz0uO2dksF8D/WGd0nubiR5MDuquxGd8A9PHjJTnNCvSJc+HoSok/9V/5ctLhRTTwjqpNkfszuAtbfNrYRSnIUOlSd+jLqvHos84bknK8I9RdPZ4WgwpjYd1LCTjrt2o6CKD9DQocDPiUQOT/Ti6D1KaNWOM8Gcx8v9aQs9r4fv27cfUsuOU22nYalXRtJl0idQKrjftvRH7SIXetqT5k+5Rbm5wgNJRKPWdf/V89kQ2NmiqyHvQyKKooKbzpRQ5AazCg8a6JWMP7+b+DxPmTb69xQDkYlY0aT/OIKLNPV0a+2jydwjTEctIzn0BezghgJI0GlkNknlQMynrBr0p7LfFYnxFmsTY5HypqvrKLLu/19FM07EfA4JnBbRnvSX7eH7Q7e1WA4zlQBQXVFZz4o83/IiP7FCOzYetSuu4prxC6WygOvwRAggKmwC5zU4vq0sU9UY394c1Em/BLLQ4ulRz1dm8H2C7DwA4H8SzcPo/ogN2SGpyjB8sHz1isKeYaqZUeJSgInVMKG7qPi0Smzy/MTNl+NGhx97dBKuFzMcg7drv6L28HLJi5FENK/wtZmz8ZED69WH+O/ENhOPFIJzPWqRcsBKeSGGI1jH8wGJwzhLp8qXkHkBjhz1h9L6xp+4wCU5k3dnwZdKQLrnzmHL4p8c6Ysk7bOYWlDKwpndMigNP3nB33VXaftqjn+I92BsD/gZzWG0BFXnnNl3vZ5Cv2ZsX60c7jFciZvV7MLHl3/S9Mp6AaSoYQB2XdD4On0kRzYzG0uz1MfM4YyFpVQ867024SwKWXa81F4dMzjEoIxmUX9ImSsz3jhsxY+TgL+nJXEnec1yTWIlF8PEFScn+9BwCCO1pI6XSv8krxI3oTXdzXmafVRpnjjNTKRdL9FuYaarYzZRyJ/EtBkgtRGLvgGbEHznpk2JzxY81kKGR4GJEQk9j+XyKwrBieIPsxuFD7LYBjFFaVspx8GzdvbbDBFYUoSYKBxsW19ENmLJ9Z05Tnst2OR0N+CsApQwB1O/MWzYbHh0fRpvCI3K7nJ0SQTDTQWtD1g/+jv6KVMqM16Tu8P3QPNdb4E6lNnY6DRrzxOLvDXJSrisuJlsGneMrnYbP1o59cf18R3ieSLYiTyBPcRshVyj1VRoqp95AISNEsaIoa1QxKS5T46q/80lgyf5rJ/1++p/tG4oq0e/bLkuN2geROp3li79LyXsJUoJCjmUSN0KSmjWAQe2hTJv08TRP+I8bQ0+eNuhaenRVByN3u5LEDS25vE2K4CtIlCNzOWINiAB4bRAybo69o5Ss2fTh48TWmyLXp43tVOyj/8FG0H8kWIScsJz7kzCqHjPIB1Dbp4h+R9OPM3i95a6ejzgA3OuxIxBGhTfJ/+mLXJTb7ZVmAV89ajTI2tEx8zi+Ff0r7vDudLJaKLw+AzLXjHLZnpvN8SbWEeV67feWjAQVmyohS/sT86BLzqyd60OVLUDNpCYR7u5VLNWlvA3gqrLfqdtaaYU5KuSN0UFhCxYToT0t80/2uSk7byMoVRH05vJzpmn6WsBpp3CPJ2BEebXAEPJxBSvNNsIVh6cHjTJc/ficet+tTjwbsKcz6ULy279OdzzXyER/Lt9PN3Z02YX/vHDWQCa2teiVtrha1rcfqf8BGtMkqiksUPfsyD5ePrhUnXM0WLvL4x/M+9cxrJQ3j6YZRRd0dhgRPRE7AUn1RxVrBKuFItEP6+qTNnGQT/5nOSDX/CypxbuUneKA4ADX7nW06ieLSIFNiNzL9RfVqKjYFXJ2UHtEqBz2K/Jt/QfnXaPDGrSrWibALa25RQ7/H/5I8GpcRdUuQ66DZy0qUaIzxeUWYhUZ+7LNLzG4BtDqTndJYkedMiHULj68ZAprJi0OHqqFWWYqoJVWSnou0GFGwhML/RaQagHG9j4RpjVcowmvjhYD8bjPoyMjCYml6gcsZPJyfyHzOGehiRaBFdXD0R25GX1v26r9E7AM+sorg==
---

